### ISSUE TITLE
files not uploading

### ISSUE THREAD

**Issue by GregDuveiller** [jhpoelen/zenodo-upload#1]
Greetings @jhpoelen!
Thanks for the nice tool. Unfortunately, after following every step and checking twice, I end up without the files uploaded. From the command line I get the progress bar working till the end and everything seems fine, but when I go to the web and refresh the page, I do not see the new files. Any clues in what is going wrong?

**Comment by jhpoelen** [comment]
Hi! Please provide details on how you run the tool and what the output is. (suggest to XXX-out the zenodo token)

**Comment by GregDuveiller** [comment]
never mind. my bad. I finally got it working. there was an error in how I gave the token. But because I was not getting any error messages and the upload seemed to work (given the progressbar), I thought it couldn't be that. Thanks for the tool!

**Comment by yyou1996** [comment]
I have a similar issue in that the progress bar goes well without seeing the uploaded files on the website.

I following the instructions as:
```
export ZENODO_TOKEN=[Zenodo access token]
./zenodo_upload.sh [deposition id] ../debug.txt -v
```

The output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1548  100  1548    0     0   3083      0 --:--:-- --:--:-- --:--:--  3083
Deposition ID: [deposition id]
File path: ../debug.txt
File name: debug.txt
Bucket URL: https://zenodo.org/api/files/b0a08e7f-d174-4753-8bdb-506cbc5a2fb3                                                                                  Uploading file...
######################################################################################################################################################## 100.0%
```

And in the Bucket URL: https://zenodo.org/api/files/b0a08e7f-d174-4753-8bdb-506cbc5a2fb3 it shows:
```
{
    "error_id": "f3493970e53c445e9611d2ef27e93471",
    "message": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
    "status": 500
}
```

I will be very appreciative of your help. Thanks.
