### ISSUE TITLE
curl: (6) Couldn't resolve host 'null' | Bucket variable returns Null value (BUCKET=null)

### ISSUE THREAD

**Issue by SaraAlthubaiti** [jhpoelen/zenodo-upload#2]
Hello @jhpoelen

Thanks for this nice and helpful tool.

I followed the same steps, clone the repository, set environment variable `ZENODO_TOKEN` to Zenodo access token, create a new publication in Zenodo and entered some information and save it, copy the deposition id and use it to upload my files but when I start doing this step of uploading files; I get this error:

```
[sarasw@cn509-02-r zenodo-upload]$ ./zenodo_upload.sh 3981464 /Sara/my_folder/sample_data.zip
+ DEPOSITION=3981464
+ FILEPATH=/Sara/my_folder/sample_data.zip
++ echo /Sara/my_folder/sample_data.zip
++ sed 's+.*/++g'
+ FILENAME=sample_data.zip
++ curl -H 'Accept: application/json' -H 'Authorization: Bearer ' https://www.zenodo.org/api/deposit/depositions/3981464
++ jq --raw-output .links.bucket
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0    219      0  0:00:01  0:00:01 --:--:--   293
+ BUCKET=null
+ curl --progress-bar -o /dev/null --upload-file /Sara/my_folder/sample_data.zip 'null/sample_data.zip?access_token='
curl: (6) Couldn't resolve host 'null'

```
Could you please help me to solve this problem?

**Comment by jhpoelen** [comment]
@SaraAlthubaiti did you manage to resolve your own issue? If so, what was the cause of the issue?

**Comment by SaraAlthubaiti** [comment]
@jhpoelen it was my fault :/ I forgot typing `export` before setting the token.

So, I did it like this:

`ZENODO_TOKEN=[Zenodo access token]`

which it should be like this:

`export ZENODO_TOKEN=[Zenodo access token]`

Thanks again for this amazing and easy to use tool :)

**Comment by jhpoelen** [comment]
Thanks for sharing and am glad to hear that you were able to make it work.

**Comment by dabail10** [comment]
I am running into the same problem and I tried to add the export line to the zenodo_upload.sh script. My default shell is tcsh, could that be the problem? I tried opening a bash session, but still had the same problem.

**Comment by jhpoelen** [comment]
@dabail10 thanks for reaching out.

To help better understand what is going on, can share a detailed example of how you are using the script? (please xxx-out the zenodo token or any other sensitive information)

**Comment by dabail10** [comment]
Thanks for taking a look and thanks for this valuable tool. Here is the output from the script. I have installed the linux build for jq in my home bin directory. Maybe the 'jq' build is not working as it should? Are there other json interpreters that I could try perhaps?

[dbailey@casper02 pcwg_dev]$ ./zenodo_upload.sh https://zenodo.org/deposit/4601647 CICE_data_gx1_forcing_JRA55_2005.tar.gz
+ DEPOSITION=https://zenodo.org/deposit/4601647
+ FILEPATH=CICE_data_gx1_forcing_JRA55_2005.tar.gz
++ echo CICE_data_gx1_forcing_JRA55_2005.tar.gz
++ sed 's+.*/++g'
+ FILENAME=CICE_data_gx1_forcing_JRA55_2005.tar.gz
++ curl -H 'Accept: application/json' -H 'Authorization: Bearer XXXX' https://www.zenodo.org/api/deposit/depositions/https://zenodo.org/deposit/4601647
++ jq --raw-output .links.bucket
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   148  100   148    0     0     66      0  0:00:02  0:00:02 --:--:--    66
+ BUCKET=null
+ curl --progress-bar -o /dev/null --upload-file CICE_data_gx1_forcing_JRA55_2005.tar.gz 'null/CICE_data_gx1_forcing_JRA55_2005.tar.gz?access_token=XXXX'

curl: (6) Could not resolve host: null; Unknown error

**Comment by jhpoelen** [comment]
Ah. The upload script expects a deposit id (e.g., 4601647) instead of a deposit url (e.g., https://zenodo.org/deposit/4601647).

I've just created a new version of the script that strips the deposit url prefix when used.

Hope this helps!

**Comment by dabail10** [comment]
That was it! My mistake. Thanks for your quick reply.
