### ISSUE TITLE
Error: curl: (28) Failed to connect to null port 80: Operation timed out

### ISSUE THREAD

**Issue by ajenney** [jhpoelen/zenodo-upload#3]
Running on mac big sur 11.2

required software versions
jq 1.6
curl  7.71.1
bash 3.2.57

**Comment by jhpoelen** [comment]
@ajenney thanks for sharing your issue. Can you please provide more information so I can help reproduce and fix the issue?

**Comment by jhpoelen** [comment]
@ajenney am closing this issue because I didn't hear from you. Please feel free to comment / re-open if your issue remains.
