### ISSUE TITLE
Exposed zenodo access token during transfer

### ISSUE THREAD

**Issue by adeslatt** [jhpoelen/zenodo-upload#4]
@jhpoelen love the tool - one security problem - one's zenodo access token is exposed during the transfer -- should change that using recommendations here:  https://community.apigee.com/articles/39911/do-you-use-curl-stop-using-u-please-use-curl-n-and.html.

or something similar....

Thanks though !   Saved me in a transfer cloud-to-cloud-to-cloud!

**Comment by jhpoelen** [comment]
hi @adeslatt - 

Thanks for sharing your concern about exposing zenodo access token. 

I've updated the upload/delete scripts to:

1. disable bash debug logging (```set -xe``` -> ```set -e```)
2. use file handle to populate curl post header to avoid exposing the token via ```ps -ef``` process lists

Please re-open / comment if this did not resolve your issue.
