### ISSUE TITLE
zenodo_upload error

### ISSUE THREAD

**Issue by zanfona734** [jhpoelen/zenodo-upload#6]
Hello,
I'm using zenodo_upload.sh with this command format:
./zenodo_upload.sh 123456 myfile.txt

It starts as expected but then returns this error:
curl: (6) Could not resolve host: null; Name or service not known

Maybe something changed on Zenodo's end since the program was written?  Any advice will be appreciated!

**Comment by yuxiangtan** [comment]
the pull request fixed this problem
