### ISSUE TITLE
Upload multiple files or directory

### ISSUE THREAD

**Issue by susheelbhanu** [jhpoelen/zenodo-upload#8]
Hi, 

Thank you for this amazing tool which makes our lives so much easier. Given my laziness, I was wondering if there was a way to upload multiple files at the same time, or even a directory.

Currently, it requires that I specify each individual file within a folder.

Thank you,
Susheel

**Comment by Kodiologist** [comment]
One can use a shell loop like `for file in file1.dat file2.dat ; do bash zenodo_upload.sh 1337420 $file ; done`, but there's no reason not to put such a loop in the script itself, and allow several filepaths as arguments.
